# /bin/sh
#
# --- Parameters ---------------------------------------------------------------
#$ -S /bin/sh
#$ -q sThC.q@@containers-hosts
#$ -N sok-2021-10-08
#$ -o 2021-10-08-sok.log
#$ -e 2021-10-08-sok.err
#$ -cwd
#$ -pe mthread 8
#$ -l mres=24G,h_data=6G,h_vmem=6G
#$ -m bea
#$ -M francois.michonneau@gmail.com

echo + `date` $JOB_NAME started on $HOST in $QUEUE jobID=$JOB_ID

# --- Modules ------------------------------------------------------------------

module load singularity

# --- Preparation --------------------------------------------------------------
mkdir -p /pool/genomics/michonneauf/sok-db

if test -f sok.simg; then
   rm sok.simg
fi

singularity pull --name sok.simg docker://ghcr.io/fmichonneau/sok-marine-biodiversity:add-docker

# --- Run Script ---------------------------------------------------------------

singularity exec --userns --bind /pool/genomics/michonneauf/sok-marine-biodiversity:/sok,/pool/genomics/michonneauf/sok-db:/var/lib/postgresql/data sok.simg Rscript -e "setwd('/sok'); remake::make()"
