# /bin/sh
#
# --- Parameters ---------------------------------------------------------------
#$ -S /bin/sh
#$ -q sThC.q@@containers-hosts
#$ -N sok-2021-10-23
#$ -o 2021-10-23-sok.log
#$ -e 2021-10-23-sok.err
#$ -cwd
#$ -pe mthread 8
#$ -l mres=24G,h_data=6G,h_vmem=6G
#$ -m bea
#$ -M francois.michonneau@gmail.com

echo + `date` $JOB_NAME started on $HOST in $QUEUE jobID=$JOB_ID

# --- Modules ------------------------------------------------------------------

module load singularity

# --- Preparation --------------------------------------------------------------

SOK_DB_DATA=/pool/genomics/michonneauf/sok-db-pg_data
SOK_DB_RUN=/pool/genomics/michonneauf/sok-db-pg_run
SOK_DB_LOG=/pool/genomics/michonneauf/sok-db-pg_log
SOK_DB_ETC=/pool/genomics/michonneauf/sok-db-pg_etc

mkdir -p /pool/genomics/michonneauf/sok-db
mkdir -p $SOK_DB_DATA
mkdir -p $SOK_DB_RUN
mkdir -p $SOK_DB_LOG
mkdir -p $SOK_DB_ETC

if test -f sok.simg; then
   rm sok.simg
fi

singularity pull --name sok.simg docker://ghcr.io/fmichonneau/sok-marine-biodiversity:add-docker

# --- Run Script ---------------------------------------------------------------

singularity exec --userns --bind /pool/genomics/michonneauf/sok-marine-biodiversity:/sok,/pool/genomics/michonneauf/sok-db:/var/lib/postgresql/data sok.simg /sok/./singularity_script.sh

singularity exec --userns \
  -B $SOK_DB_DATA:/var/lib/postgresql \
  -B $SOK_DB_RUN:/var/run/postgresql \
  -B $SOK_DB_LOG/:/var/log/postgresql \
  -B $SOK_DB_ETC:/etc/postgresql \
  sok.simg /sok/./singularity_script.sh